### ISSUE TITLE
ACEX Fortification CBA Settings Non-Existant

### ISSUE THREAD

**Issue by BSherb** [acemod/ACEX#103]
**Arma 3 Version:** `1.80` (stable / rc / dev)
**CBA Version:** `3.5 (stable / dev + commit hash)
**ACE3 Version:** `3.12.1` (stable / dev + commit hash)
**ACEX Version:** `3.x.x` (stable / dev + commit hash) 

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- No CBA Settings for ACEX Fortify

**Steps to reproduce:**
- Launch the game with ACEX

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- ACEX Fortification (Required because of no CBA setting)

**RPT log file:**
- No Log made

**Comment by jonpas** [comment]
As far as I see there isn't supposed to be any. It's handled using a module, which makes sense in this case. I believe you can also place multiple of them to set different value for different sides.

@PabstMirror

**Comment by BSherb** [comment]
Alright, I was just told to make an issue tracker by "Alganthe"
Because Konig told me not to place any more modules because everything is being switched to CBA.

**Comment by jonpas** [comment]
Yeah I've seen that, wasn't able to answer at the time though. Modules are not obsolete for things like this, because they just make more sense when you are able to place more.

**Comment by BSherb** [comment]
Alright, well you guys do you.
This way I don't have to pester Konig about CBA

**Comment by jonpas** [comment]
Same reason as ACE3 Slideshow and some other few components still use modules. They were never even ACE Settings.

**Comment by PabstMirror** [comment]
https://ace3mod.com/wiki/featurex/fortify.html

I don't think settings make sense for this, you can place different modules for each side (and control the preset on each)
