### ISSUE TITLE
Standalone Headless Client - Feature Request

### ISSUE THREAD

**Issue by MitchJC93** [acemod/ACEX#104]
**Feature Request**

Is it possible for you guys to release your ACEX Headless Client function as a standalone mod? It's a great mod and we use it on our ACE/ACEX missions but cannot use it on our public server as this has no dependencies.

I've done some testing on this and confirm it works if I run it as a -servermod on the server and -mod on the HC. Only issue is this means the server is running ACE and ACEX including the keys. This causes all sorts of conflict issues as well as allowing players to connect with ACE enabled.

**Comment by Dorbedo** [comment]
Why don't you just delete every pbo exept main and headless?
It's a modular mod.

**Comment by MitchJC93** [comment]
Tried that, it still has ACE dependencies.

**Comment by jokoho48** [comment]
but only on ace_common and ace_main.

**Comment by jokoho48** [comment]
so you need
ace_main.pbo
ace_module.pbo
ace_common.pbo
acex_main.pbo
acex_headless.pbo

and then just sign then your self.

**Comment by jonpas** [comment]
As per license if someone wants to make it standalone, go ahead, there is even a possibility you could run it under ACETeam officially, but at this time we have no plans of making it standalone. As said above, there is very little interesting for it being standalone, and really no real reason (alternatives above).

**Comment by bux** [comment]
>  but cannot use it on our public server as this has no dependencies

**Comment by jonpas** [comment]
You can use it server+HC only, thus signing them yourself so they can only be used for HC.
