### ISSUE TITLE
[Fortify] Emit CBA events when creating and deleting objects in the fortify framework

### ISSUE THREAD

**Issue by dixon13** [acemod/ACEX#106]
Emit local CBA events when an object is placed and deleted with ACEX_fortify.

**Comment by dixon13** [comment]
Should the event that gets emitted be local to client, server, or global?

**Comment by dixon13** [comment]
Emitting an event allows mission makers and mod makers to add more functionality when placing/removing objects.

**Comment by dixon13** [comment]
Would need to emit event here when removing
https://github.com/acemod/ACEX/blob/master/addons/fortify/XEH_postInit.sqf#L51

and here when placing objects
https://github.com/acemod/ACEX/blob/master/addons/fortify/functions/fnc_deployConfirm.sqf

**Comment by Vegas** [comment]
Looking for a way to get ACEX Fortify to communicate with ALiVE Logistics so that objects can be saved to a database.

Looks like I would need to modify when an object is released or, confirm placement and have it update position to be "watched".

Here is how it is accomplished with R3F Logistics

[ALiVE_SYS_LOGISTICS,"updateObject",[R3F_LOG_joueur_deplace_objet]] call ALIVE_fnc_logistics;

Any suggestions are happily appreciated.

ALiVE Documentation: 
http://alivemod.com/wiki/index.php/Logistics_Support

**Comment by dixon13** [comment]
That wouldn't work. This is actually why I submitted this ticket, to get an event to emit so I can use ACEX Fortify instead of R3F. The event will allow you to run custom code whenever an object is placed and removed. @Vegas 

FYI `ALIVE_fnc_logistics` has 3 arguments
1. logic for the module
2. method name
3. arguments to pass to method, which in this case is an array of objects to update with the database, or profile if saving locally

**Comment by dixon13** [comment]
Last I saw in Slack, I think we are waiting for @jonpas to chime in and see if we should emit local or global CBA event.

**Comment by Vegas** [comment]
@dixon13 What about this:

[ALiVE_SYS_LOGISTICS,"updateObject",[acex_fortify_fnc_deployConfirm]] remoteExecCall ["ALIVE_fnc_logistics", 2]

**Comment by PabstMirror** [comment]
Let me know if #110 has what you need
2 events are
`[QGVAR(objectPlaced), [_unit, _side, _newObject]] call CBA_fnc_globalEvent;`
`[QGVAR(objectDeleted), [_player, _side, _target]] call CBA_fnc_globalEvent;`

**Comment by Vegas** [comment]
@PabstMirror 

Ok, it looks like #110 would solve everything. Stoked on this revision!

For ALiVE database you could run something that would look like this:

[ALiVE_SYS_LOGISTICS,"updateObject",[acex_fortify_objectPlaced]] remoteExecCall ["ALIVE_fnc_logistics", 2]

@dixon13 I'm curious, which database are you using for object persistence? Are you actually using the ALiVE DB or something else like inidbi2?

**Comment by dixon13** [comment]
@PabstMirror works for me.

@Vegas I'm using local save. Local save just stores huge array of data to profile. I don't like it but I use it for auto saving, since war room doesn't support auto saving.
When #110 is merged, we will be able to just use a mission script to handle saving to db like so,

```SQF
if (isServer) then {
    ["acex_fortify_objectPlaced", {
        [ALIVE_SYS_LOGISTICS, "updateObject", [(_this select 2)]] call ALIVE_fnc_logistics;
    }] call CBA_fnc_addEventHandler;

    ["acex_fortify_objectDeleted", {
        [ALIVE_SYS_LOGISTICS, "removeObject", [(_this select 2)]] call ALIVE_fnc_logistics;
    }] call CBA_fnc_addEventHandler;
};
```
