### ISSUE TITLE
Feature Request - Fortify - Ability To Create Categories In Menu

### ISSUE THREAD

**Issue by Vegas** [acemod/ACEX#113]
There may already be a way to do this, but I am unsure how!

When defining a list of custom classnames to be used in the fortify system, once the menu is opened, only about 22 items max can be displayed due to UI limitation. All items are consolidated into a single list.

It would be great if we had the ability to create categories and define what those categories are. This would solve the space issue, and also make it easier to find things.

**Example:**

Bunkers
Walls
Roadblock
Misc

and so on.

**Comment by hessloch** [comment]
This issue can be circumvented by just going straight to adding the selfActions through a new config.

I'm not sure that the provided registerObjects function has any means of adding children actions, but it's not too big a deal to make use of these wonderful acex_fortify functions in your own selfActions.
```
    class Man;
    class CAManBase: Man {
        class ACE_SelfActions {
            class New_Fortify {
                displayName = "New Fortify";
                condition = "true";
                statement = "[west, 99999, [['Land_BagBunker_Small_F']] call acex_fortify_fnc_registerObjects;";
                exceptions[] = {};
                showDisabled = 0;
                priority = 1;
		class Barriers {
		        displayName = "Barriers";
		        condition = "true";
			class Bag_Bunker {
				displayName = "Bag Bunker";
				statement = "[player, player, [west, 'Land_BagBunker_Small_F']] call acex_fortify_fnc_deployObject";;
		   };
		};
            };
        };
    };
```

Just add the class of the object you'd like to register in the statement of your Fortify declare. Then call deployObject on the classname of the object youi'd like to spawn. This could probably be cleaned up a lot by creating your own functions that extend acex_fortify, so you don't have to pass those arguments over and over again, if you only want to do this for one side and don't care about budget.

Additionally, this creates two fortify self actions, so you can either enable this by default and never mess with the tool item, or you could probably overwrite the Fortify config, but I haven't really looked at how ACE "class ADDON" works yet, so I'm not going to speak on that part.
