### ISSUE TITLE
ACEX Sitting - Sitting Resets When A Player Crashes

### ISSUE THREAD

**Issue by Vegas** [acemod/ACEX#119]
This is a reoccurring issue that seems to still be persisting.

Basically, when a player in server crashes or lags out, it makes everybody stand up if they are sitting.

Super annoying bug for milsim units that use chairs for briefing rooms and/or debriefs.

**Comment by jonpas** [comment]
What version? This wqs supposed to be  at least partially fixed in 3.3.0, so please fill out the template.

**Comment by Vegas** [comment]
Confirmed this issue is still happening on the latest version of ACEX (3.3.0)

CBA is latest version (v3.6.1.180131)

We generally have 30+ players per mission and experience this every night. Not sure if everyone sitting in the same area (we have rows of chairs) could cause any issue here.

**Comment by jonpas** [comment]
Please check this again after 3.4.0 releases.
