### ISSUE TITLE
Feature Request - Fortify - Display cost of item at start of item interaction point text

### ISSUE THREAD

**Issue by Drofseh** [acemod/ACEX#121]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.1` (stable)
**ACEX Version:** `3.3.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- Currently the Fortify interaction point shows the remaining budget available
- It would be nice if each item had its own cost at the start of the text for its interaction point
* $50 - Bunker
instead of just
* Bunker
- This would allow faster resource management planning as there would no longer be a need to select an object and go into placement mode in order to see the cost.

**Steps to reproduce:**
- activate any fortify mode with a budget

**Where did the issue occur?**
- Editor (Singleplayer)

**Comment by dedmen** [comment]
This is ongoing and assigned. Bad bot.

**Comment by Drofseh** [comment]
No Bot no!

**Comment by Drofseh** [comment]
No Bot no!
