### ISSUE TITLE
Fortify: Feature Request - onPlacedCode

### ISSUE THREAD

**Issue by Tennessee-Timmy** [acemod/ACEX#125]
https://github.com/acemod/ACEX/blob/master/addons/fortify/functions/fnc_registerObjects.sqf

^ needs a 3rd parameter for object code

https://github.com/acemod/ACEX/blob/master/addons/fortify/functions/fnc_deployConfirm.sqf

^ needs to run code specific to that class from registered objects

I tried placing a car and it exploded on placement. (having custom code there I could disable damage for the car and then later enable it when it's safe)
Would be nice to place an ammobox and have a script run on it that adds specific gear.

**Comment by mharis001** [comment]
There is the`acex_fortify_objectPlaced` global event which can be used to achieve what you want.

**Comment by PabstMirror** [comment]
I think just using `acex_fortify_objectPlaced` is the best bet
e.g.
```
["acex_fortify_objectPlaced", {
  params ["_unit", "_side", "_object"];
  if ((typeOf _object) == "myAmmoBoxClassname") then {
    // do thing    
  };
}] call CBA_fnc_addEventHandler
```
