### ISSUE TITLE
Feature Request: Add item cost to Fortify placement.

### ISSUE THREAD

**Issue by TahMahn** [acemod/ACEX#143]
Fairly straightforward. Interested in knowing if it would be possible to add an item cost to building items. E.g. placing down a sandbag wall costs a sandbag, razor wire fence costs razor wire, etc. 

Thanks :)

**Comment by Cuel** [comment]
This is already possible?

**Comment by Drofseh** [comment]
I think there is some confusion between you two.

Fortifications can only be assigned a dollar cost, you can't use game objects as the cost.

**Comment by TahMahn** [comment]
Ah, oh well. Thanks for clarifying! :)

**Comment by PabstMirror** [comment]
We could add new items that would work as tokens.
like a "sandbag bunker" item, would be used instead of a team wide cost
