### ISSUE TITLE
Too many objects are viable water sources

### ISSUE THREAD

**Issue by bux** [acemod/ACEX#148]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.9.0` (stable)
**ACE3 Version:** `3.12.4` (stable)
**ACEX Version:** `3.4.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- e.g. car wrecks and blood pools are counted as water sources.

**Steps to reproduce:**
- Open and start attached mission
- Open Zeus, place down a unit and shoot "yourself"
- Observe blood pools coming from the body
- Try to interact with the body
- Observe blood pools acting as water sources

![20181130192948_1](https://user-images.githubusercontent.com/1235520/49308293-2bd08800-f4d8-11e8-89dc-638eaa5957f6.jpg)

**Where did the issue occur?**
- Editor (Singleplayer)

**Additional information:**
- We need to change the way objects are treated as water sources. Better have some sort of whitelist for specific objects and don't use base classes

**RPT log file:**

[ACEX-WaterSources-Mission_and_RPT.zip](https://github.com/acemod/ACEX/files/2634599/ACEX-WaterSources-Mission_and_RPT.zip)

**Comment by madpat3** [comment]
also rocks and bushes
![20181130195619_1](https://user-images.githubusercontent.com/15272840/49309574-f29a1700-f4db-11e8-8e53-531b4113e641.jpg)
![Uploading 20181130200258_1.jpg…]()

**Comment by Drofseh** [comment]
But what if I _want_ to drink the blood of my enemies?
The trees should definitely be kept as well, to simulate Canadians drinking maple syrup.
=D

**Comment by madpat3** [comment]
yes, and inside or under rocks, there might be a well.

**Comment by LeightonThompson** [comment]
Yeah, sadly this makes this unusable.
We had issues that it was blocking the ACE interacts on people, meaning that we couldn't provide medical support to people unconscious due to their blood pool.
IMO, a good temporary fix would be allowing us to disable refilling entirely.

**Comment by LeightonThompson** [comment]
Thanks for your great work on getting these patches done so soon!
When can we expect to see these pushed to steam workshop?
