### ISSUE TITLE
Interaction distance for water sources is too high

### ISSUE THREAD

**Issue by bux** [acemod/ACEX#149]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.9.0` (stable)
**ACE3 Version:** `3.12.4` (stable)
**ACEX Version:** `3.4.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
![20181130192808_1](https://user-images.githubusercontent.com/1235520/49309765-a00d2a80-f4dc-11e8-80b9-12af2ab901ab.jpg)

**Steps to reproduce:**
- Open and start attached mission
- Observe: interaction distance is too damn high
![image](https://user-images.githubusercontent.com/1235520/49309791-ad2a1980-f4dc-11e8-96ac-cd0c8dd17f6c.png)

**Where did the issue occur?**
- Editor (Singleplayer)

**RPT log file:**

[ACEX-WaterSources-Mission_and_RPT.zip](https://github.com/acemod/ACEX/files/2634599/ACEX-WaterSources-Mission_and_RPT.zip)

**Comment by mharis001** [comment]
Agreed, I think the default distance of 2 should be good (instead of current 5.5).

**Comment by PabstMirror** [comment]
I might have picked a high value for those large "bladders" when the interaction point was center of object.
We now have a nice interaction point on a valve at the edge, so the long reach isn't needed.
