### ISSUE TITLE
Items and Objects, that don't work with the "Field Ration System" + CUP objects

### ISSUE THREAD

**Issue by madpat3** [acemod/ACEX#151]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.9.0` (stable)
**ACE3 Version:** `3.12.4` (stable)
**ACEX Version:** `3.4.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- Well, these items/objects have Water inside, or could be filled with Water, but have no Interaction Points, to do such things.

Bohemia:
Land_PaperBox_01_open_water_F;
Land_WaterBottle_01_stack_F;
Land_WaterBottle_01_pack_F;
Land_WaterBottle_01_full_F;
Land_WaterBottle_01_empty_F;
Land_WaterBottle_01_compressed_F;
Land_Balloon_01_water_F;
Land_WaterTower_01_F;
Land_ConcreteWell_01_F

CUP:
watertank_04_f.p3d
watertank_01_f.p3d
watertank_02_f.p3d
(Land_pumpa) pumpa.p3d

**Steps to reproduce:**
- Place these things on map and try to refill it or from it or drink out of it.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer

**Comment by Will-Nichols** [comment]
@madpat3 have you tried this with a dedicated as well?

**Comment by madpat3** [comment]
most of them, because that was the reason i was diggin into this. it happened on a dedicated, then i tried out others as well, but only on local-mp
