### ISSUE TITLE
Field Rations: Add option to disable refilling

### ISSUE THREAD

**Issue by bux** [acemod/ACEX#155]
title

**Comment by PabstMirror** [comment]
I think at some point we will add "Drink from water source"
do we want to just disable refilling or diable all interactions with water sources?

**Comment by bux** [comment]
I'd like to see all interactions being disabled by a setting. We could think about splitting this setting to accommodate for the different interactions.

**Comment by bux** [comment]
Bad bot.... Don't you dare ....

**Comment by Will-Nichols** [comment]
Maybe use items like crates of water as is mentioned in #151 ?

**Comment by bux** [comment]
Bad bot.... Don't you dare ....
