### ISSUE TITLE
ACEX Sitting bug

### ISSUE THREAD

**Issue by Kile467** [acemod/ACEX#158]
**Arma 3 Version:** `1.88 stable` (stable / rc / dev)
**CBA Version:** ` v3.9.0.181012` (stable / dev + commit hash)
**ACE3 Version:** `3.12.5 stable` (stable / dev + commit hash)
**ACEX Version:** `3.4.1 stable` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- ACEX
```

**Description:**
- ACEX animation for sitting is the same all the time, and sometimes it clips with the back of the chair depending of the type of chair.

**Steps to reproduce:**
- Sit down in any chair avalaible for sitting.

**Where did the issue occur?**
- Dedicated, Self-Hosted Multiplayer, Singleplayer

**Additional information:**
- With the wicker chair the animation is slightly moved to the right, not in the middle of the chair.

**RPT log file:**
Graphic bug, not necessary.

**Comment by jonpas** [comment]
- Are you sure it's always the same? All. Animations look similar but they are all. A bit different, one is picked at random.
- Nothing can be done with clipping, you can even lean back and be crazy haha. That's just a downside of how it works most reliably.
- Can you provide classname of the wicker chair?

**Comment by Kile467** [comment]
- It looks like at least. Before the update sitting animations were very different and never caused clipping with the chairs (one lean back, another was correctly sit, another one lean back slightly to the front...) Now it is always lean back and clipping...
- Before the update the animation never caused clipping at all... I think it is the kind of animations that you are using, and the position of the character in each chair.
- Sure: I think it was **Land_RattanChair_01_F** or **Land_ChairPlastic_F**
--

**Comment by jonpas** [comment]
Animations and positions on those chairs are unchanged.

Can you get a screenshot example?
