### ISSUE TITLE
Incorporate stamina regeneration similar to MGM Foods

### ISSUE THREAD

**Issue by Will-Nichols** [acemod/ACEX#162]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.0.181012` (stable)
**ACE3 Version:** `3.12.5` (stable)
**ACEX Version:** `3.4.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
- SMA 2.7.1
- RHSUSAF
- VME PLA Mod
- NI Arms All in One
- ACE 3 Extension (Animations and Actions)
- 15th Airborne PLA
- Spyder Addons
- SMA Sound Fix 1.68
- ACE Compat - RHS USAF
- ALiVE
- Diwakos ACE Ragdolling
- ACE 3 Extension (Placeables)
- MGM Foods
- M3A1 SpecOps Tanoa-Edition
- Enhanced Movement
- MELB Standalone version
- ILBE Assault Pack (TFAR)
- ILBE Assault Pack RF-3800 Fix
- L3-GPNVG18 Panoramic Night Vision
- VSM All In One Collection
- TFAR Beta
- Injured AI
- fen_A3
- Survivable Crashes
- Criminal Intervention Gendarmerie Tanoa
- NI Arms All in One ACE Compatibility
- TFR Tanoa Takedown Mission ACE 3 Files (ace3_nouniformrestriction pbo only)
- SMA NIArms RHS Compatibility Mod
- Achilles
```

**Description:**
- Attempted to use MRE and water in our mission and we were unable to access them. We could not eat or drink but we were able to see the items in the mission and pick them up and carry them around but not able to eat or drink at all. Also did not have any indicators on the HUD even after restarting server to ensure CBA settings were enabled.

**Steps to reproduce:**
- Add items to your inventory and attempt to eat or drink.

**Where did the issue occur?**
- Dedicated Multiplayer

**Additional information:**
- It is entirely possible that there is a conflict with MGM Foods and ACEX Rations. We have MGM in the mission first but wanted to try ACEX Rations as a different aspect. We were still able to eat the MRE from MGM but we were unable to drink the items they have in the game. I am working on a basic ACE, CBA, Vanilla repro mission and will also do one where I have MGM in it as well to see if there is a conflict.

**RPT log file:**
- [https://www.dropbox.com/s/pkjxlfapdhy4yoh/arma3server_x64_2018-12-18_01-52-59.rpt?dl=0](Link to the Server RPT file.)

**Comment by mharis001** [comment]
Could be a conflict but can you double check your settings. You should have the base "Survival` self interaction whenever field rations is enabled.

Also, ensure that you were not trying to consume the MGM items with ACEX field rations, that will not work unless those items have the necessary config values for ACEX.

**Comment by Will-Nichols** [comment]
>           Could be a conflict but can you double check your settings. You should have the base "Survival` self interaction whenever field rations is enabled.
> Also, ensure that you were not trying to consume the MGM items with ACEX field rations, that will not work unless those items have the necessary config values for ACEX.

Settings are correct but we did not have the "Survival" self interaction appearing. We only had the interactions with MGM item by moving over to the head on the medical menu.

**Comment by mharis001** [comment]
The "Survival" self interaction only has the condition `acex_field_rations_enabled` so it is very weird that the action wouldn't show if field rations was enabled. That leaves it to a conflict but that wouldn't explain the base action not showing.

https://github.com/acemod/ACEX/blob/master/addons/field_rations/CfgVehicles.hpp#L7

**Comment by Will-Nichols** [comment]
Almost 100% guarantee that it was a conflict with MGM but that is only found on locally hosted dedicated server; its my house hold game server. About to put it out on the server for our community and see if that fixed it.

**Comment by Will-Nichols** [comment]
OK determined it was due to a MGM Foods conflict. 

Can you give me any information on the Humanitarian Ration and if it is something that we could use to pass out to AI via Spyder Addon's or any other civilian interaction module?

**Comment by mharis001** [comment]
Glad it worked out. The Humanitarian Ration is the same as all the other MREs apart from the name of course. You would need to add a custom script for a reputation system if that is what you are trying to do. Hope that helps.

**Comment by Will-Nichols** [comment]
Is it possible to incorporate the stamina regeneration system like what MGM has with the items that are in this addition? Maybe make them have a slightly detrimental effect on the player like they would in real life without additional food and water? Maybe have a need for water refill #155 since you increased heart rate and respiration by using the items that regenerated stamina.

**Comment by mharis001** [comment]
I am not sure what system MGM Foods has in terms of stamina but additional effects for consuming items can be added by mission makers using the newly added events.

**Comment by Jstinii** [comment]
@mharis001 With the newest update, if you satisfy a person's hunger/thirst, would it restore a person's stamina?

**Comment by bux** [comment]
No. And you won't see that in ACE or ACEX. It's just not how it works in real life. But as a mission maker, you could add that yourself. That's what @mharis001 was referring to.
