### ISSUE TITLE
Feature request: Field rations, add cba event when ration is eaten/ drunk

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [acemod/ACEX#171]
Pretty much everything is in the title a local cba EH would allow us to do extra stuff (i'm planning on adding a few consumable items including alcohol and I'd like to run a script when it's consumed).
Suggestion: pass consumed classname to the eh.

**Comment by dedmen** [comment]
https://github.com/acemod/ACEX/pull/159

**Comment by MisterHLunaticwraith** [comment]
My bad, I'd browsed the code before asking but totally missed it!
