### ISSUE TITLE
Field Rations needs ability to disable for individual units eg Zeus

### ISSUE THREAD

**Issue by NZF-JDWang** [acemod/ACEX#172]
Currently with no way to disable thirst and hunger on an individual basis, it's easy for a dedicated Zeus to pass out from dehydration/hunger in the middle of a mission.

A editor attribute which stops thirst/hunger affecting a unit would be most useful.

**Comment by bux** [comment]
Feature requests go to:
https://github.com/acemod/ACE3/issues/3594/

**Comment by Dystopian** [comment]
@bux this looks more like bug report
