### ISSUE TITLE
Question: ACEX Field Rations are affected by time acceleration?

### ISSUE THREAD

**Issue by byjokese** [acemod/ACEX#173]
**Arma 3 Version:** `x.xx` Latest Stable
**CBA Version:** Latest Stable
**ACE3 Version:** `3.12.5` (stable)
**ACEX Version:** `3.4.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
```

Are the field rations affected by acceleration time? So far setting to max, seems no to affect? Is that a bug or intentional?

**Comment by mharis001** [comment]
Do you mean `accTime` or `timeMultiplier`? `accTime` is only in single player and does affect field rations, `timeMultiplier` does not.

**Comment by byjokese** [comment]
Okey nice to know!
