### ISSUE TITLE
Feature Request: exec custom script when item consumed (Field Rations)

### ISSUE THREAD

**Issue by Vegas** [acemod/ACEX#178]
Requesting the ability to execute a custom script when an item is consumed within Field Rations.

Mentioned this on Slack a few weeks ago, not sure if it's already on the radar.

o7

**Comment by dedmen** [comment]
Already solved 3 months ago: https://github.com/acemod/ACEX/pull/159
Can be closed.

**Comment by PabstMirror** [comment]
Feature will come in next release (3.4.2) - which should be soonish

**Comment by Vegas** [comment]
@PabstMirror No worries! Thanks for your hard work guys. o7
