### ISSUE TITLE
Naked units transfer bug (#163) persists

### ISSUE THREAD

**Issue by PirkleAwesome** [acemod/ACEX#180]
**Arma 3 Version:** `1.90` (stable / rc / dev)
**CBA Version:** `3.10.0.190316` (stable / dev + commit hash)
**ACE3 Version:** `3.12.6` (stable / dev + commit hash)
**ACEX Version:** `3.4.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- Units lose their load out when transferring to HC (All sides, vanilla & mods)

https://gfycat.com/PlasticInsidiousBlacklab   (Project Opfor Independent ChDKZ Insurgents, RHS AFRF  OPFOR Russia (MSV), Vanilla BLUFOR NATO

**Steps to reproduce:**
- Spawn units
- Wait

**Where did the issue occur?**
- Dedicated

**Additional information:**
- Server config settings  https://pastebin.com/uG6KHvTb

**Comment by jonpas** [comment]
Are server settings also set on headless clients?

**Comment by PabstMirror** [comment]
Getting rpt from hc will be really helpful
mainly looking for the presence of `Unit [%1] became local with broken loadout - attempting to fix`

**Comment by jonpas** [comment]
Maybe `uniform UNIT == ""` is not true yet right after transfer, but only some frames later when sync catches up.

**Comment by PirkleAwesome** [comment]
@jonpas I don't know if the server settings are on the headless clients. I am not the main person responsible for my units server, so Ill have to ask him when get gets on.

@PabstMirror https://pastebin.com/knfvSZf8  rpt mentions broken load out at lines 2596 - 2615

**Comment by PirkleAwesome** [comment]
@jonpas The server config is indeed set on the headless clients.

**Comment by jonpas** [comment]
> Maybe `uniform UNIT == ""` is not true yet right after transfer, but only some frames later when sync catches up.

Looking at RPT, that's clearly not the case and works correctly.

Maybe "Local" EH fires before loadout variable on the unit gets transferred over the network? That also doesn't make good sense, because variable should be undefined, not an empty loadout in that case, and it should fall-back to config-defined loadout.

**Comment by Freddo3000** [comment]
Sometimes for me the units appear with a uniform, however they do not keep vest, helmet and weapons, leaving them unarmed. You can sometimes see them walking around fine, and then suddenly have their gear removed.

Seemingly only appears on busy MP servers.

Relevant BI-FT ticket? https://feedback.bistudio.com/T127183

**Comment by jonpas** [comment]
Seems like the improvement to the current workaround would be to wait longer before checking if transfer failed and reapplying the loadout.

**Comment by jannes-io** [comment]
Had a couple of naked guys running around today, so I went into our server logs and we've encountered the same log that was posted here prior. These 3 lines always appear to follow up on each other:
`
16:06:50 [ACEX] (headless) INFO: Unit [B Ghosts:9] became local with broken loadout - attempting to fix
16:06:50 Ref to nonnetwork object 2c24f5c8e80# 1254101: rhsusf_uniform_acu.p3d
16:06:55 Warning: Cleanup player - person 2:2375 not found
`

Any update? Is acex responsible for naked players? In our case it keeps everything except for the uniform, and the player does see his own uniform, it's just others that can't see it.

**Comment by jonpas** [comment]
No, it's not ACEX responsible directly, just Arma synchronization that is slow.

**Comment by jonpas** [comment]
Possible improvements (thanks to @Freddo3000 @oOKexOo):
- Check additional items (eg. vest, helmet, weapon) - but only if they are non-empty in loadout as well (should really do the same for uniforms as well anyways)
- Assure loadout is available on the receiving machine before applied (right now transfer happens immediately after publishing loadout)
  - Additionally only transmit to the target machine, not everyone
