### ISSUE TITLE
Field Rations: Spectator also has hunger and thirst

### ISSUE THREAD

**Issue by jonpas** [acemod/ACEX#187]
**Arma 3 Version:** `1.94` (stable)
**CBA Version:** `3.12.0` (stable)
**ACE3 Version:** `3.12.6` (stable)
**ACEX Version:** `3.4.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- Spectator keeps draining water and food level.
- Spectator shows water and food level UI.

**Steps to reproduce:**
- Enable Field Rations, use Spectator.

**Where did the issue occur?**
- All

**Additional information:**
- None

**RPT log file:**
- N/A

**Comment by PabstMirror** [comment]
Any spectator or the dedicated "virtual spectator" unit things?

**Comment by jonpas** [comment]
Encountered with ACE Spectator opened with `[true, false] call ace_spectator_fnc_setSpectator`.
