### ISSUE TITLE
Feature Request - Allow custom unit names in ACEX kill tracker

### ISSUE THREAD

**Issue by simkas** [acemod/ACEX#194]
I noticed that the kill tracker currently gets the name of the unit that it displays in the kill info directly from the unit config. It would be nice to be able to set some kind of variable or something on AI units  to make the kill info use that custom name instead of just the class display name. This would be useful for cases when the enemy units being used have custom mission enforced loadouts instead of just using the basic classes.

**Comment by dedmen** [comment]
> to set some kind of variable or something on AI units to make the kill info use that custom name instead of just the class display name

https://community.bistudio.com/wiki/setName

Close?

**Comment by simkas** [comment]
The ACEX kill tracker doesn't use that name, does it?

**Comment by dedmen** [comment]
You mean this?
https://github.com/acemod/ACEX/blob/master/addons/killtracker/XEH_postInit.sqf#L116
See
https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_getName.sqf



> I noticed that the kill tracker currently gets the name of the unit that it displays in the kill info directly from the unit config. 

not sure if you mean the "killed" unit or the "killer" unit.

**Comment by simkas** [comment]
Oh I guess I didn't quite make that clear in the original post, I mean the unit that was killed. If that unit was AI, its name is taken from the config.
[https://github.com/acemod/ACEX/blob/9bdc1f7d5a42f2a5fc9789b9e70a6c0ccdef60f6/addons/killtracker/XEH_postInit.sqf#L130]

**Comment by PabstMirror** [comment]
Would something like this work for you?
Lets you setVar `acex_killTracker_aiName` to anything

```
private _name = _unit getVariable ["acex_killTracker_aiName", ""];
if (_name == "") then { _name =  format ["*AI* - %1", getText (configfile >> "CfgVehicles" >> (typeOf _unit) >> "displayName")]; };
```

another option would be to add a setting to just use ace_fnc_getName instead of the `*AI*` thing

**Comment by simkas** [comment]
Having a name variable that is used if it is set and having it use the config name when that isn't set sounds pretty great.
