### ISSUE TITLE
Fortify: Adding ACE_draggable and/or ACE_carryable to Fortify object overlaps each other and remove action

### ISSUE THREAD

**Issue by luckyspoon** [acemod/ACEX#209]
**Arma 3 Version:** `1.84` stable
**CBA Version:** `3.12.1` stable
**ACE3 Version:** `3.13.1` stable
**ACEX Version:** `3.5.0` stable

**Mods:**
```
- CBA_A3
- ace
- acex
- 2x custom modpacks
- CUP Terrains Core & Maps
- RHS x4
- TFAR
- ST Hud
```

**Description:**
This is a follow up from my quick exchange in the ACE Slack.

We wanted to make fortify deployed objects movable, so after placement we call
```
	[_newObject, true] call ace_dragging_fnc_setDraggable;
	[_newObject, true] call ace_dragging_fnc_setCarryable;
```
However, this makes the two new interaction options overlap with the default "Remove Object" interaction, which makes all 3 options basically unusable.

I have specifically tested this with `Land_BagFence_01_long_green_F`, however, I see no reason it would differ object-to-object.

I can provide a copy of our patch mod which automatically calls Draggable and Carryable if that's of assistance.

**Steps to reproduce:**
- Fortify an object
- Call `setDraggable` and `setCarryable` on the new object
- ACE Interact with the new object, overlapped.

**Where did the issue occur?**
- Only tested on dedicated servers & multiplayer from the Editor

**RPT log file:**
I don't think it's needed but can get if required

**Comment by PabstMirror** [comment]
I think fortify just adds a base action (instead of main_actions), 
I will look into this
