### ISSUE TITLE
ACEX Food persistence

### ISSUE THREAD

**Issue by Pyth3rEx** [acemod/ACEX#224]
**Is your enhancement related to a problem?**
Kinda, there is no way to persist player food levels between disconnects.

**Solution you'd like:**
Ability to use solutions such as [GRAD-Persistence](https://github.com/gruppe-adler/grad-persistence) or other softwares to save these values or having an option/module directly implemented into ACEX to do so.

**Alternatives you've considered:**
I have tried understanding the code and using GRAD to save the values, issue is I am unable to reapply them to the player when he reconnects due to my lack of knowledge is arma scripting.

**Additional context:**
I think that's all

**Comment by mharis001** [comment]
The variable names are `acex_field_rations_thirst` and `acex_field_rations_hunger` on the player's varspace, both with a range from 0 to 100. You can just set the values you saved when the player reconnects and everything should work as expected.

**Comment by Pyth3rEx** [comment]
So I've been fidling with what you told me for a bit now but my lack of knowledge is a pain here.

I am using grad-persistence in which I am saving these custom variables.

**Comment by Pyth3rEx** [comment]
So I've been fidling with what you told me for a bit now but my lack of knowledge is a pain here.

I am using grad-persistence in which I am saving these custom variables.
```
        class acexFood {
            varName = "acex_field_rations_hunger";
            varNamespace = "player";
            public = 1;
        };
        class acexWater {
            varName = "acex_field_rations_thirst";
            varNamespace = "player";
            public = 1;
        };
```

This being said you said "set the values you saved when the player reconnects" wich I don't know how to do. I found the onPlayerConnected function with wich I started a script:
init.sqf
```
//Apply persistent values
onPlayerConnected "[_uid] execVM ""persistence.sqf""";
```
persistence.sqf
```
player setVariable ["acex_field_rations_thirst", "acex_field_rations_thirst"]
player setVariable ["acex_field_rations_hunger", "acex_field_rations_hunger"]
```

Of course that dosn't work as I'm expecting a few syntax errors? Idk how to tacle that problem.

**Comment by mharis001** [comment]
Depends on the persistence system, by "set the values you saved when the player reconnects" I meant the actual values 0 to 100 - which it looks like grad-persistence will do for you when you specify them as custom variables. You can always check if the correct values have been applied using `getVariable`. Hope that helps.

**Comment by Pyth3rEx** [comment]
I've been setting them as custom variables but they don't seem to get saved for whatever reason.

**Comment by mharis001** [comment]
A problem with that would be on grad-persistence's side. Closing as the question regarding setting up persistence for `acex_field_rations` has been addressed.

**Comment by Pyth3rEx** [comment]
So ACE food works??? I guess? It just worked... I guess I'll just leave that there and not mind it XD
Thanks for your help!!!
