### ISSUE TITLE
Automatic mission ending when no players are present

### ISSUE THREAD

**Issue by TheConen** [acemod/ACEX#24]
**Arma 3 Version:** `1.60` 
**CBA Version:** `2.4.1`
**ACE3 Version:** `3.6.0`
**ACEX Version:** `3.0.0`

**Mods:**
- `@CBA_A3`
- `@ace`
- `@acex`

**Description:**
When a HC is present, servers that have "persistent = 0;" in the server config, will never end the mission. An optional setting in the module to automatically end the mission and return to the mission selection screen or load the default mission when only HCs are present, would be very nice.

**Steps to reproduce:**
Load a mission with a HC on a server that has "persistent = 0" and have every player exit. The mission will still continue to run though it shouldn't.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- ACEX - Headless Client

**RPT log file:**
Not relevant.

**Additional information:**
We currently use this script in missions, but it would be very nice to have that as a server-side enforceable setting.
```
addMissionEventHandler ["HandleDisconnect",{
    private _numberOfPlayer = {!(typeOf _x == "HeadlessClient_F")} count allPlayers;
    if(_numberOfPlayer == 0) then {
        [] call BIS_fnc_endMissionServer;
    };
}];
```

**Comment by brainslush** [comment]
Would make that an optional feature b/c if one has an persistent server, you will end up with the reverse effect. Mission stops even though the server is persistent

**Comment by bux578** [comment]
e.g. ALiVE missions

**Comment by jonpas** [comment]
Check the pull request, of course it's optional, we also run our in-house persistence system. ;)
