### ISSUE TITLE
Question: AceX Headless Client

### ISSUE THREAD

**Issue by kwinteng** [acemod/ACEX#33]
**Arma 3 Version:** latest
**CBA Version:** latest
**ACE3 Version:** `3.6.2`
**ACEX Version:** `3.0.0`

I'm very new to the whole headless client bit, my question here is: will AceX offload (or try to offload) units that are placed live in Zeus by curators or only those from the editor?

Also sidenote to maintainer: maybe change the CBA Version to 3.x.x since i think it went to 3 now instead of 2

**Comment by jonpas** [comment]
> will AceX offload (or try to offload) units that are placed live in Zeus by curators or only those from the editor?

Yes it will. It will try to rebalance every time something new is spawned, but if it's not an AI unit it simply won't do anything.

> Also sidenote to maintainer: maybe change the CBA Version to 3.x.x since i think it went to 3 now instead of 2

Good point.
