### ISSUE TITLE
Question: AceX Headless Client activity

### ISSUE THREAD

**Issue by kwinteng** [acemod/ACEX#34]
**Arma 3 Version:** latest stable
**CBA Version:** latest stable
**ACE3 Version:** `3.6.2` 
**ACEX Version:** `3.0.0` 

I'm sorry to ask another trivial question but is there a way see to see the activity of AI being pushed to the headless client using the ACEX module? (RPT log or otherwise?)

Thanks for all your replies and help guys

**Comment by jonpas** [comment]
You could have just used the same issue. ;)

Yes, there is a setting for logging. Either in module or using ACE3's Settings framework.

Please hop up on our [Slack](http://slackin.ace3mod.com/) for further questions.

**Comment by kwinteng** [comment]
Alright, that helps and i will in the future @jonpas 
My appologies :)
