### ISSUE TITLE
"File ace_sitting.pbo is outdated"

### ISSUE THREAD

**Issue by Slowrider8** [acemod/ACEX#39]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.1.161012` (stable)
**ACE3 Version:** `3.8.0.10` (stable)
**ACEX Version:** `3.1.0.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@acex`

**Description:**
Attempting to run any mission provides an error after launch stating that "File ace_sitting.pbo is outdated." and then force ends the mission.  Image of error: http://puu.sh/rNEtF/b45e9de8b9.jpg

Occuring with entirely untouched mods and without any additional mods running.

**Steps to reproduce:**
- Place player unit in blank editor mission
- Start Mission
- Experience error

**Where did the issue occur?**
Editor (Singleplayer)

**Placed Modules:**
None

**RPT log file:**
http://pastebin.com/07F6xMZR

**Comment by PabstMirror** [comment]
ace_sitting in acex has acex's version config
https://github.com/acemod/ACEX/blob/master/addons/sitting/config.cpp#L26

**Comment by Glowbal** [comment]
Resolved for 3.1.1.
