### ISSUE TITLE
Feature request, opt-in headless

### ISSUE THREAD

**Issue by Arcanum417** [acemod/ACEX#52]
Feature request:

It would be great to have an option to use headless transfer as opt-in rather than opt-out. I would imagine a switch in server/mission settings if only groups marked with this setVariable ["acex_headless_blacklist", true]; should be left out or only these groups should be transfered. And have a zeus module you could place on a group to toggle this variable.

This is in regard to my previous issue.

**Comment by jonpas** [comment]
I won't be implementing this, it makes it more confusing to use and the idea of headless is to keep it simple.

You can accomplish the same by simple setting blacklist variable on all of them except those you don't want. Should work by doing it in `initServer.sqf` in the mission.
