### ISSUE TITLE
Don't transfer groups with synchronized triggers to HC

### ISSUE THREAD

**Issue by maxx87** [acemod/ACEX#54]
Feature request:

Dont transfer Groups where waypoint with trigger is present, like ...

	//found local, created by commy
	private _allGroups = allGroups select {!isPlayer leader _x};

	{
		private _group = _x;
		private _allWaypointsWithTriggers = waypoints _group select {!(synchronizedTriggers _x isEqualTo [])};

		if (_allWaypointsWithTriggers isEqualTo []) then {
			... transfer ...
		};
	} forEach _allGroups;

**Comment by jonpas** [comment]
I like this! Even better would be if we could move those triggers with them somehow.

**Comment by mr-bo-jangles** [comment]
This script claims to do just that: http://www.armaholic.com/page.php?id=28917
