### ISSUE TITLE
Units lose all clothing/gear/weapons on transfer to HC

### ISSUE THREAD

**Issue by tanaaKa** [acemod/ACEX#62]
**Arma 3 Version:** `1.64` stable
**CBA Version:** `3.12` stable
**ACE3 Version:** `3.9.0` stable
**ACEX Version:** `3.1.1` stable

**Mods:**
- `@CBA_A3`
- `@ace`
- `@acex`
- `@acre2`
- `@asr_ai`
- `@bloodlust`
- `@niarsenal`
- `@projectopfor`
- `@RHSAFRF`
- `@RHSGREF`
- `@RHSUSAF`
- `@CUP_Terrains`

**Description:**
When spawning units through zeus during a multiplayer session, units lose all gear during transfer. The amount of units that lose gear are random, but generally, the more units you spawn at once, the more that lose their gear.

Video of the bug:
https://youtu.be/Rcwuh6vJJqM

**Steps to reproduce:**
With the above running mods, spawn any amount of AI groups with zeus. Once HC transfer begins, 1 or more units will lose all clothing/gear/weapons.

**Where did the issue occur?**
Dedicated Multiplayer Session

**Placed Modules:**
ACE Nametags
ACE Medical Settings
ACE Point
ACE UI
ACE Advanced Fatigue
ACE Advanced Throwing
ACE MK6 Settings
ACE Map Gestures
ACEx Headless

**RPT log file:**
RPT was cleared earlier today by another developer. Will update with latest rpt after our sunday session (in ~18 hours).

**Comment by bux** [comment]
duplicate #48
