### ISSUE TITLE
Headless does not transfer all AI when 2 HCs are present

### ISSUE THREAD

**Issue by jonpas** [acemod/ACEX#64]
Round-robin logic doesn't work properly for 2 HCs. Works fine for 1 HC as it's all transfer to that one in that case, and for 3 HCs, but for 2 it fails as one of them will be `null`.

**Comment by bux** [comment]
>27.02.2017 - 00:51
>jonpas
>all tested and working

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 138 days without any activity.

**Comment by shukari** [comment]
Is this issue still a problem?

**Comment by jonpas** [comment]
Yes.

**Comment by ramius86** [comment]
Got a similar problem, with 3 HC, rebalancing isn't accurate.
1 HC 30 AI
2 HC 50 AI
3 HC 50 AI
or similar numbers

**Comment by jonpas** [comment]
@ramius86 Not a similar problem .It all depends on how your AI is grouped, only groups as whole are transferred, not separate AI.

Also if it occasionally goes a bit off, that's fine too, especially if units are spawned in post-start.
