### ISSUE TITLE
ACEX Sitting Resets When A Player Crashes

### ISSUE THREAD

**Issue by Vegas** [acemod/ACEX#67]
Arma3 1.68.. and prior

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- Players sitting in chairs are forced to stand up when another player in the server crashes to desktop OR simply disconnects.

**Steps to reproduce:**
- Need two players in a server
- One player sit in chair
- Other player disconnects
*OR*
- Other player simulate a CTD by hitting ESC>ALT+F4 (or some more creative method)
- Sitting player will be forced to stand up after Steam Ticket Check Fail of "CTD"

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Placed Modules:**
- ACEX_Sitting

**Comment by jonpas** [comment]
My best guess is the chair gets moved by the desync that happens when someone crashes.
Adding some leeway [here](https://github.com/acemod/ACEX/blob/9a5c9cee92623bcf48de2bdae992857320a433eb/addons/sitting/functions/fnc_sit.sqf#L68) might fix it.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 130 days without any activity.
