### ISSUE TITLE
Chair can't be used again after switching the chair

### ISSUE THREAD

**Issue by nic547** [acemod/ACEX#68]
All versions the current steam versions
**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- When switching a chair while not getting up in-between will make the old one unsitable (until carried around).

**Steps to reproduce:**
- Place multiple chairs
- Directly switch from one chair to another (without getting up)

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- ACEX Sitting Module

**Comment by jonpas** [comment]
Already fixed in #45

**Comment by nic547** [comment]
woops i'm sorry

**Comment by jonpas** [comment]
There is a reason you are using that avatar, right? 😆
