### ISSUE TITLE
Error in expression - Headless

### ISSUE THREAD

**Issue by Fallingstorm** [acemod/ACEX#71]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.1` (stable)
**ACEX Version:** `3.2.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
- AI_Alive
- CUP Units, Vehicles, Weapons
- HMD
- mcc
- stHUD
- TFAR
- AH64
- AWS
- FA18
- MELB
- Nimitz
- SAM
- UH60
- MilGearPack
- MRT
- SMA
```

**Description:**
- The error fils the RPT-log
 
**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
- None

**RPT log file:**
RPT ist to BIG it has 112 MB  :O

here a schort cut: Line 32425 Time Code 20:14:56 to Line 1505874 Time Code  22:03:32

20:14:56 [ACEX] (headless) INFO: Present HCs: [HC1] - Full Rebalance: true
20:14:56v<transfer = !(units _x isEqualTo []) && {!(_x getVariable ["acex_headless_blackli>
20:14:56   Error position: <!(_x getVariable ["acex_headless_blackli>
20:14:56   Error !: Type Number, expected Bool
20:14:56 File z\acex\addons\headless\functions\fnc_transferGroups.sqf, line 54
20:14:56 [ACEX] (headless) INFO: Present HCs: [HC1] - Full Rebalance: true
20:14:56 Error in expression <transfer = !(units _x isEqualTo []) && {!(_x getVariable ["acex_headless_blackli>
20:14:56   Error position: <!(_x getVariable ["acex_headless_blackli>
20:14:56   Error !: Type Number, expected Bool
20:14:56 File z\acex\addons\headless\functions\fnc_transferGroups.sqf, line 54
20:14:56 [ACEX] (headless) INFO: Present HCs: [HC1] - Full Rebalance: true
20:14:56 Error in expression <transfer = !(units _x isEqualTo []) && {!(_x getVariable ["acex_headless_blackli>
20:14:56   Error position: <!(_x getVariable ["acex_headless_blackli>
20:14:56   Error !: Type Number, expected Bool
20:14:56 File z\acex\addons\headless\functions\fnc_transferGroups.sqf, line 54
20:14:56 [ACEX] (headless) INFO: Present HCs: [HC1] - Full Rebalance: true
20:14:56 Error in expression <transfer = !(units _x isEqualTo []) && {!(_x getVariable ["acex_headless_blackli>
20:14:56   Error position: <!(_x getVariable ["acex_headless_blackli>
20:14:56   Error !: Type Number, expected Bool
20:14:56 File z\acex\addons\headless\functions\fnc_transferGroups.sqf, line 54
.
.
.
22:03:32 [ACEX] (headless) INFO: Present HCs: [HC1] - Full Rebalance: true
22:03:32 [ACEX] (headless) INFO: Groups Transferred: Total: 17 - HC1: 17 - HC2: 0 - HC3: 0
22:03:32 [ACE] (cookoff) WARNING: no valid selection for cookoff found.  z\ace\addons\cookoff\functions\fnc_cookOff.sqf:34
22:03:32 [ACE] (cookoff) WARNING: no valid selection for cookoff found.  z\ace\addons\cookoff\functions\fnc_cookOff.sqf:34

Hope you can help

**Comment by jonpas** [comment]
This is something on your end, I can't reproduce (not even with 1 HC like in your case).

**Comment by Fallingstorm** [comment]
heureka, i have the RPT for you
https://www.dropbox.com/s/hom8rlc3edr1zkm/arma3-2server_x64_2017-04-06_19-59-10.rpt?dl=0

Oh i think we had 2 HC but have a look on the rpt

**Comment by jonpas** [comment]
Unless you can reproduce this with just `@CBA_A3` and `@acex`, this is not a bug, but an issue on your end.

That RPT is spammed with errors and warnings unrelated to ACEX.

**Comment by PabstMirror** [comment]
Try running this code and seeing if anything shows up in systemChat
```
{
    private _var = _x getVariable ["acex_headless_blacklist", false];
    if (!(_var isEqualType false)) then {
        systemChat format ["Unit %1 [%2] has bad var [%3]", _x, typeOf _x, _var];
    };
} forEach allUnits;
```

**Comment by Fallingstorm** [comment]
hm ok then beginns the run to finde a needle.
Ok i will do a look for.

**Comment by Fallingstorm** [comment]
OK Update.
We startet the same Mission and the rpt-entries was not reproduced.
I think we can this Issue Close. Must be an error at our side.
