### ISSUE TITLE
Automatic vehicle volume toggle turn off if open map

### ISSUE THREAD

**Issue by shukari** [acemod/ACEX#74]
# **Arma3 Vanilla Bug: https://feedback.bistudio.com/T125415**

**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable
**ACEX Version:** stable

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- The automatic volume toggle turned off if you in a vehicle open your map.
Video: https://youtu.be/9Sn_JYNyTDY

**Steps to reproduce:**
- Turn on automatic vehicle volume toggle
- fade to 1 sec
- go in vehicle (helicopter for sound)
- open Map

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- to many

**RPT log file:**
- https://gist.github.com/shukari/4a30fa6b14c50ee9115a80d3471410b4

**Comment by jameslkingsley** [comment]
I can't seem to reproduce this bug, volume stays lowered when I open the map while inside a vehicle (tried with wheeled and helicopters).

**Comment by shukari** [comment]
Video: https://youtu.be/9Sn_JYNyTDY

**Comment by PabstMirror** [comment]
I've noticed this with just ace_hearing earplugs
I'm betting that `fadeSound` doesn't have any effect when on the 2d map

**Comment by shukari** [comment]
No, fadeSound and the map have no problems, i tested it with `5 fadeSound 0` and on the map was also nothing to hear. That must be in the ace and acex code.

**Comment by jameslkingsley** [comment]
Isn't that just a feature/bug of Arma? I've always noticed that when I open the map inside a moving helicopter, the sound of the heli will fade away, as if the sound is coming from the perspective of the map and the map is left behind. What it sounds like in the video is that the map is outside the vehicle.

**Comment by jonpas** [comment]
What @jameslkingsley said, I don't think we even can fix that, not for this volume nor for earplugs themselves.

**Comment by shukari** [comment]
Ähm... `fadeSound` worked on map and i tested it on vanilla... but a bug in ACE(X) reset the `fadeSound` if you open the map. Nothing to do with the thing that the sound source on map is creepy.
