### ISSUE TITLE
Sitting in air

### ISSUE THREAD

**Issue by Tress16** [acemod/ACEX#80]
**Arma 3 Version:** `1.72` (stable / rc / dev)
**CBA Version:** `3.4.0` (stable / dev + commit hash)
**ACE3 Version:** `3.10.2` (stable / dev + commit hash)
**ACEX Version:** `3.2.0` (stable / dev + commit hash)

**Mods:**
- CBA_A3
- ace
- acex
- ALiVE
- Enhanced Movement
- Heros Survive
- SMA
- Task Force Radio
- VSM - All In One Collection
- BackpackOnChest

**Description:**
I think sitting on chairs (ACEX Mod) is broken since the last update of Enhanced Movement. Now I'm sitting 0.5m higher in the air. My friend using the x32 Arma version and had no problems. The problems are only with x64 Arma version (?). I have reported the issue at EM dev BadBanson too.

https://forums.bistudio.com/forums/topic/174788-enhanced-movement/?page=41#comment-3216446

**Steps to reproduce:**
- Placing a ACE-handled chair and try to sit on with the upper listed modlist.

**Where did the issue occur?**
- Dedicated Server

**Placed Modules:**
- Using ace-server.pbo.

**RPT log file:**
- Can find no entry in the log file.

**Comment by bux** [comment]
So, does it happen with only CBA, ACE3 and ACEX?

**Comment by jonpas** [comment]
No, it happen only with Enhanced Movement, it has been reported before and is not an ACEX issue, I don't know what weird magic Enhanced Movement does.

**Comment by bux** [comment]
@jonpas close?

**Comment by commy2** [comment]
ref #88
