### ISSUE TITLE
Cannot add drone units to ACEX HC blacklist

### ISSUE THREAD

**Issue by olanguedoc** [acemod/ACEX#81]
**Arma 3 Version:** `1.74` (stable)
**CBA Version:** `3.40` (stable )
**ACE3 Version:** `3.10.2` (stable )
**ACEX Version:** `3.2.0` (stable)

**Mods:**
```
- CBA_A3
- ACE
- ACEX
```

**Description:**
When using ACEX HC on a dedicated server with 3HC, You loose control of the drones after a couple minutes when you leave the interface. We guess that it is transfered to the HC.  The drone isnt responding to inputs on the Drone interfance either.

Our suggestion is to add the ACEX Blacklist attributes to Drone also... by default so the smaller backpack drone can also inherit the attribute.

**Steps to reproduce:**
- Fly drone manually.
- Give it a waypoint via the interface.
- Go to camera mode. 
- Get out of the drone interface and back to 3rd person. 
- Wait 2-3 minutes
- Go back in, try to give it another waypoint. (at that point he might already be doing circle somewhere)

**Where did the issue occur?**
- Dedicated server, with 3 HC et around 10-20 players online.

**Placed Modules:**
- We use ACE Server Config. 

- Advanced Medical
- Advanced Ballistic

**RPT log file:**
- will try to provide one.

**Comment by olanguedoc** [comment]
[VIDEO WITH ACEX HC "ON" ](https://www.youtube.com/watch?v=0QN_QpEk8w8&feature=youtu.be)
[VIDEO WITH ACEX HC "OFF"](https://www.youtube.com/watch?v=oojbCSCWUNM&feature=youtu.be)

**Comment by jonpas** [comment]
I think we should just prevent drones from transferring in ACEX. No point transferring them if they just break.

**Comment by olanguedoc** [comment]
I am doing some more testing on this. I'll keep you posted.

**Comment by jonpas** [comment]
I completely forgot AI actually is the drone. When you connect your pad to it then locality gets transferred to you (I assume), thus it would of course break if it gets transferred to HC. I will prepare a fix for you to test.

**Comment by olanguedoc** [comment]
Anything you want me to test out Jonpas?

**Comment by jonpas** [comment]
I didn't get around to fixing this yet.
