### ISSUE TITLE
Allow server to own part of units

### ISSUE THREAD

**Issue by shukari** [acemod/ACEX#94]
It would be nice if there is not only the option all or nothing... i would be great if i can also add the server to the round robin chain... i can only host one hc but this one dont run all units smooth... so it would be nice if some units stay on the server.

**Comment by MitchJC93** [comment]
You could just blacklist the units you want to stay on the server:

`this setVariable ["acex_headless_blacklist", true];`

**Comment by PabstMirror** [comment]
I think this might be best left to just scripting
like mitch said you can just use setVar to leave some groups on the server

this should give you a 50% mix:
```
private _aiGroups = allGroups select {({isPlayer _x} count (units _x)) == 0};
diag_log text format ["AI Groups: %1", count _aiGroups];
{
    if ((random 1) < 0.5) then {
        _x setVariable ["acex_headless_blacklist", true, true];
        diag_log text format ["Group [%1] will run on server", _x];
    };
} forEach _aiGroups;
```

**Comment by dixon13** [comment]
close? @BaerMitUmlaut
